# Site settings
title: Coding Blog
header-img: img/home-bg.png
email: ruandisheng@gmail.com
copyright_name: fattyduck
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code at Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fattyduck
learn_profile: fattyduck
email_username: ruandisheng@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
